#include "format_analyzer.h"
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

static void note(char *n,size_t z,const char *s){size_t u;if(!n||!z||!s)return;u=strlen(n);if(u<z-1)strncat(n,s,z-u-1);}
static uint32_t be32(const unsigned char *p){return ((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];}
static uint16_t be16(const unsigned char *p){return (uint16_t)(((uint16_t)p[0]<<8)|p[1]);}
static uint32_t le32(const unsigned char *p){return (uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static uint64_t satmul(uint64_t a,uint64_t b){return (a && b>UINT64_MAX/a)?UINT64_MAX:a*b;}

int af_analyze_gzip(FILE *fp,uint64_t fs,AfGzipMetrics *m,char *n,size_t z){unsigned char h[10],t[8];if(!fp||!m||fs<18)return -1;memset(m,0,sizeof(*m));rewind(fp);if(fread(h,1,10,fp)!=10||h[0]!=0x1f||h[1]!=0x8b)return -1;m->compression_method=h[2];m->flags=h[3];if(fseek(fp,-8,SEEK_END)!=0||fread(t,1,8,fp)!=8)return -1;m->trailer_isize=le32(t+4);m->compressed_bytes=fs;m->declared_uncompressed_bytes=m->trailer_isize;m->isize_wrap_possible=(m->trailer_isize==0 && fs>18);m->expansion_ratio=(fs?((double)m->trailer_isize/(double)fs):0.0);if(m->compression_method!=8)note(n,z,"GZIP uses a non-DEFLATE compression method. ");if(m->isize_wrap_possible)note(n,z,"GZIP ISIZE is modulo 2^32; true expanded size may exceed the trailer value. ");return 0;}
unsigned int af_score_gzip(const AfGzipMetrics *m,char *n,size_t z){unsigned int s=0;if(!m)return 25;if(m->expansion_ratio>=1000){s+=70;note(n,z,"Extreme GZIP expansion ratio. ");}else if(m->expansion_ratio>=100){s+=45;note(n,z,"High GZIP expansion ratio. ");}else if(m->expansion_ratio>=20){s+=20;note(n,z,"Elevated GZIP expansion ratio. ");}if(m->isize_wrap_possible)s+=15;return s>100?100:s;}

static int octal(const unsigned char *p,size_t n,uint64_t *v){size_t i=0;uint64_t x=0;while(i<n&&(p[i]==' '||p[i]=='\0'))i++;for(;i<n&&p[i]>='0'&&p[i]<='7';i++){if(x>(UINT64_MAX-7)/8)return 0;x=x*8+(p[i]-'0');}*v=x;return 1;}
int af_analyze_tar(FILE *fp,uint64_t fs,AfTarMetrics *m,char *n,size_t z){unsigned char b[512];uint64_t off=0;unsigned zeros=0;if(!fp||!m)return -1;memset(m,0,sizeof(*m));rewind(fp);while(off+512<=fs&&m->entry_count<1000000){uint64_t sz=0,padded;size_t r=fread(b,1,512,fp);if(r!=512)break;off+=512;{size_t i;int all=1;for(i=0;i<512;i++)if(b[i]){all=0;break;}if(all){zeros++;if(zeros>=2)break;continue;}zeros=0;}if(!octal(b+124,12,&sz)){m->malformed_headers++;break;}m->entry_count++;m->total_declared_bytes+=sz;if(sz>m->largest_entry_bytes)m->largest_entry_bytes=sz;if(b[156]=='2'||b[156]=='1')m->link_entry_count++;if((b[0]=='/' )||(isalpha(b[0])&&b[1]==':'))m->absolute_path_count++;if(strstr((const char*)b,"../")||strstr((const char*)b,"..\\"))m->path_traversal_count++;padded=(sz+511u)&~511ull;if(off+padded>fs){m->malformed_headers++;break;}if(fseek(fp,(long)padded,SEEK_CUR)!=0)break;off+=padded;}m->declared_to_file_ratio=fs?((double)m->total_declared_bytes/(double)fs):0.0;if(m->entry_count>=1000000)note(n,z,"TAR entry scan limit reached. ");return 0;}
unsigned int af_score_tar(const AfTarMetrics *m,char *n,size_t z){unsigned int s=0;if(!m)return 25;if(m->entry_count>100000){s+=50;note(n,z,"Very high TAR entry count. ");}else if(m->entry_count>10000)s+=25;if(m->declared_to_file_ratio>100)s+=25;if(m->path_traversal_count){s+=40;note(n,z,"TAR path traversal entries detected. ");}if(m->absolute_path_count)s+=25;if(m->malformed_headers)s+=15;return s>100?100:s;}

int af_analyze_png(FILE *fp,uint64_t fs,AfImageMetrics *m,char *n,size_t z){unsigned char b[29];unsigned channels=4;(void)n;(void)z;if(!fp||!m||fs<29)return -1;memset(m,0,sizeof(*m));rewind(fp);if(fread(b,1,29,fp)!=29)return -1;if(memcmp(b,"\x89PNG\r\n\x1a\n",8)!=0||memcmp(b+12,"IHDR",4)!=0)return -1;m->width=be32(b+16);m->height=be32(b+20);m->bit_depth=b[24];m->color_type=b[25];switch(m->color_type){case 0:channels=1;break;case 2:channels=3;break;case 3:channels=1;break;case 4:channels=2;break;case 6:channels=4;break;default:channels=4;}m->components=channels;m->pixel_count=satmul(m->width,m->height);m->estimated_decoded_bytes=satmul(m->pixel_count,channels*((m->bit_depth>8)?2:1));m->decoded_to_file_ratio=fs?((double)m->estimated_decoded_bytes/(double)fs):0.0;return 0;}
int af_analyze_jpeg(FILE *fp,uint64_t fs,AfImageMetrics *m,char *n,size_t z){unsigned char a[2];(void)n;(void)z;if(!fp||!m||fs<4)return -1;memset(m,0,sizeof(*m));rewind(fp);if(fread(a,1,2,fp)!=2||a[0]!=0xff||a[1]!=0xd8)return -1;while(ftell(fp)>=0&&(uint64_t)ftell(fp)+4<fs){int c;unsigned char lenb[2];uint16_t len;do{c=fgetc(fp);if(c==EOF)return -1;}while(c!=0xff);do{c=fgetc(fp);if(c==EOF)return -1;}while(c==0xff);if(c==0xd9||c==0xda)break;if(c>=0xd0&&c<=0xd7)continue;if(fread(lenb,1,2,fp)!=2)return -1;len=be16(lenb);if(len<2)return -1;if((c>=0xc0&&c<=0xc3)||(c>=0xc5&&c<=0xc7)||(c>=0xc9&&c<=0xcb)||(c>=0xcd&&c<=0xcf)){unsigned char sof[6];if(len<8||fread(sof,1,6,fp)!=6)return -1;m->bit_depth=sof[0];m->height=be16(sof+1);m->width=be16(sof+3);m->components=sof[5];m->pixel_count=satmul(m->width,m->height);m->estimated_decoded_bytes=satmul(m->pixel_count,m->components?m->components:3);m->decoded_to_file_ratio=fs?((double)m->estimated_decoded_bytes/(double)fs):0.0;return 0;}if(fseek(fp,(long)len-2,SEEK_CUR)!=0)return -1;}return -1;}
unsigned int af_score_image(const AfImageMetrics *m,uint64_t fs,char *n,size_t z){unsigned int s=0;(void)fs;if(!m)return 25;if(m->pixel_count>1000000000ull){s+=80;note(n,z,"Extreme decoded pixel count. ");}else if(m->pixel_count>250000000ull){s+=60;note(n,z,"Very high decoded pixel count. ");}else if(m->pixel_count>100000000ull)s+=35;else if(m->pixel_count>40000000ull)s+=15;if(m->decoded_to_file_ratio>1000)s+=20;else if(m->decoded_to_file_ratio>100)s+=10;return s>100?100:s;}
